# Custom configuration for joint calling Strelka2 whole genome sequencing gVCFs.
unifier_config:
    drop_filtered: true
    min_allele_copy_number: 1
    min_AQ1: 35
    min_AQ2: 20
    min_GQ: 20
    max_alleles_per_site: 0
    monoallelic_sites_for_lost_alleles: true
    preference: common
genotyper_config:
    revise_genotypes: false
    min_assumed_allele_frequency: 0.0001
    required_dp: 0
    allow_partial_data: false
    allele_dp_format: AD
    ref_dp_format: DP
    output_residuals: false
    squeeze: false
    output_format: BCF
    liftover_fields:
        - orig_names: [MIN_DP, DP, DPI]
          name: DP
          description: '##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">'
          type: int
          number: basic
          default_type: missing
          count: 1
          combi_method: min
          ignore_non_variants: true
        - orig_names: [AD]
          name: AD
          description: '##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">'
          type: int
          number: alleles
          combi_method: min
          default_type: zero
          count: 0
          ignore_non_variants: true
        - orig_names: [GQ]
          name: GQ
          description: '##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">'
          type: int
          number: basic
          default_type: missing
          count: 1
          combi_method: min
          ignore_non_variants: true
        - orig_names: [FILTER]
          name: FT
          description: '##FORMAT=<ID=FT,Number=1,Type=String,Description="FILTER field from sample gVCF">'
          type: string
          number: basic
          default_type: missing
          combi_method: missing
          count: 1
          ignore_non_variants: true
        - orig_names: [ADF]
          name: ADF
          description: '##FORMAT=<ID=ADF,Number=.,Type=Integer,Description="Allelic depths on the forward strand">'
          type: int
          number: alleles
          default_type: zero
          combi_method: min
          count: 0
          ignore_non_variants: true
        - orig_names: [ADR]
          name: ADR
          description: '##FORMAT=<ID=ADR,Number=.,Type=Integer,Description="Allelic depths on the reverse strand">'
          type: int
          number: alleles
          default_type: zero
          combi_method: min
          count: 0
          ignore_non_variants: true
